### PR TITLE
Fix for Layout Change message

### PR DESCRIPTION
**Pull request by AGulev**
If I understand everything right

### CODE REVIEW

**Comment by AGulev** [comment]
No, it's still broken but in the other place

**Comment by britzl** [comment]
I added a unit test and included the fix anyway, because it was an actual problem you found.

https://github.com/britzl/monarch/commit/909ada9f18803519495c8c9f4bf786ffbaa5919b

**Comment by AGulev** [comment]
Even with this fix, sometimes I don't see my buttons at all (it seems like they stay out of the screen), I'm not sure why. There are no errors in the log. I fount temporary workaround: use `transitions.instant` if it's the first run of the scene (because it happens only on start).
But yes, this fix is actual anyway

**Comment by britzl** [comment]
Hmm, ok, so still something related to transitions and layout/orientation change? I wonder if we can reproduce this in a test somehow?

**Comment by AGulev** [comment]
not sure (
I tried many times, but I can't only on this old device I don't have direct access to.

**Pull request closed without merging**
