### PR TITLE
Implement monarch.replace()

### LINKED ISSUE #60: Feature request: Replace the top of the stack instead of pushing
There are situations where you want linear navigation instead of nested navigation (progressing through the story, for example). I'd add a `pop: number` field to the `options` of `monarch.show()` that pops a given number of scenes from the top of the stack before adding the new screen.

For example, `pop = 1` would be used to replace the currently shown screen at the top of the stack with another one.

What do you think of this change? If it's ok with you design-wise, I can open a PR.

### PR DESCRIPTION
**Pull request by dapetcu21**
Implement being able to replace the top of the stack, as discussed on #60.

Closes #60

### CODE REVIEW

**Comment by dapetcu21** [comment]
I was expecting to have messed up the tests, but I honestly wasn't expecting an engine crash:
```
INFO:CRASH: Successfully wrote Crashdump to file: /home/travis/.Defold/_crash
2782
2783./dmengine_headless(+0x259787) [0x562d7531c787]
2784/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890) [0x7f23fbf41890]
2785./dmengine_headless(+0x1c78fb) [0x562d7528a8fb]
2786./dmengine_headless(+0x1a1b50) [0x562d75264b50]
2787./dmengine_headless(+0x1b0eec) [0x562d75273eec]
2788./dmengine_headless(+0x1b1645) [0x562d75274645]
2789./dmengine_headless(+0x19f837) [0x562d75262837]
2790./dmengine_headless(+0x54708) [0x562d75117708]
2791./dmengine_headless(+0x3f0c6) [0x562d751020c6]
2792./dmengine_headless(+0x320c6) [0x562d750f50c6]
2793./dmengine_headless(+0xa8ab6) [0x562d7516bab6]
2794./dmengine_headless(+0x34ed1) [0x562d750f7ed1]
2795./dmengine_headless(+0x34fb5) [0x562d750f7fb5]
2796./dmengine_headless(+0x30a2b) [0x562d750f3a2b]
2797/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f23fb01cb97]
2798./dmengine_headless(+0x3087a) [0x562d750f387a]
2799
2800./.travis/run.sh: line 41:  7129 Segmentation fault      (core dumped) ./dmengine_headless --config=bootstrap.main_collection=${DEFOLD_BOOSTRAP_COLLECTION}
2801The command "./.travis/run.sh" exited with 139.
```

**Comment by dapetcu21** [comment]
I'll amend this commit and rebase the branch, maybe this kicks Travis to make a new build.

**Comment by dapetcu21** [comment]
Yup. I could repro the crash in the editor.

**Comment by britzl** [comment]
Only when running headless?

**Comment by dapetcu21** [comment]
Nope, even when running directly in the editor with the test bootstrap collection.

**Comment by dapetcu21** [comment]
Meanwhile, let me rebase this.

**Comment by britzl** [comment]
```
# 0 pc   0x137a95fd MetadataUtilities _sigtramp+29
# 1 pc     0x1454a2 dmengine lua_settop+98
# 2 pc     0x116e3f dmengine _ZN8dmScript14InvokeCallbackEPNS_15LuaCallbackInfoEPFvP9lua_StatePvES4_+271
# 3 pc     0x124b0e dmengine _ZN8dmScriptL16LuaTimerCallbackEPNS_10TimerWorldENS_14TimerEventTypeEjfmm+78
# 4 pc     0x1239a6 dmengine _ZN8dmScript12UpdateTimersEPNS_10TimerWorldEf+294
# 5 pc     0x115def dmengine _ZN8dmScript17UpdateScriptWorldEPNS_11ScriptWorldEf+79
# 6 pc      0x152d7 dmengine _ZN12dmGameObject16CompScriptUpdateERKNS_22ComponentsUpdateParamsERNS_22ComponentsUpdateResultE+71
# 7 pc      0x1fa19 dmengine _ZN12dmGameObject6UpdateEPNS_16CollectionHandleEPKNS_13UpdateContextE+617
# 8 pc       0x52ca dmengine _ZN8dmEngine4StepEPNS_6EngineE+906
# 9 pc      0x71246 dmengine _ZN10dmGraphics18RunApplicationLoopEPvPFvS0_EPFiS0_E+38
#10 pc       0x6071 dmengine _ZN8dmEngine6LaunchEiPPcPFvPNS_6EngineEPvES6_S4_+177
#11 pc       0x649f dmengine _Z11engine_mainiPPc+143
```

**Comment by dapetcu21** [comment]
Apparently the merge fixed it. Here's the old crashing commit: https://github.com/dapetcu21/monarch/tree/replace-crashing

**Comment by britzl** [comment]
Very strange indeed. It no longer crashes for me either.

**Pull request merged**
